Repository aws/karpenter-provider-aws, pull requests merged in 2021-11, with the labels that each got.

#790 Doc updates in support of promoting capacity-type to a well known label
  website/content/en/docs/cloud-providers/AWS.md
  website/content/en/docs/faqs.md
  website/content/en/docs/getting-started/_index.md
  website/content/en/docs/provisioner-crd.md
Labels: documentation

#773 launchtemplate docs
  website/content/en/docs/cloud-providers/AWS/_index.md
  website/content/en/docs/cloud-providers/AWS/aws-spec-fields.md
  website/content/en/docs/cloud-providers/AWS/launch-templates.md
Labels: documentation

#788 Adds design doc to discuss Karpenter limits
  designs/limits.md
Labels: design

#777 Create main Karpenter concepts doc
  website/config.toml
  website/content/en/docs/_index.md
  website/content/en/docs/concepts/_index.md
Labels: documentation

#801 enable versioning for docs site
  website/config.toml
  website/content/en/docs/cloud-providers/AWS/aws-spec-fields.md
  website/content/en/pre-docs/_index.md
  website/content/en/pre-docs/cloud-providers/AWS/_index.md
  website/content/en/pre-docs/cloud-providers/AWS/aws-spec-fields.md
  website/content/en/pre-docs/cloud-providers/AWS/launch-templates.md
  website/content/en/pre-docs/cloud-providers/_index.md
  website/content/en/pre-docs/development-guide.md
  website/content/en/pre-docs/faqs.md
  website/content/en/pre-docs/getting-started/_index.md
  website/content/en/pre-docs/getting-started/cloudformation.yaml
  website/content/en/pre-docs/getting-started/grafana-values.yaml
  website/content/en/pre-docs/getting-started/prometheus-values.yaml
  website/content/en/pre-docs/provisioner-crd.md
  website/content/main.py
  website/layouts/partials/hooks/body-end.html
Labels: documentation

#829 add GitHub stars button
  website/content/en/_index.html
  website/content/en/pre-docs/getting-started/_index.md
  website/layouts/shortcodes/github.html
Labels: hacking

#837 move grafana to subpage
  website/content/en/pre-docs/getting-started/_index.md
  website/content/en/pre-docs/getting-started/grafana.md
Labels: documentation

#841 remove old code for github button
  website/content/en/_index.html
  website/layouts/shortcodes/github.html
Labels: documentation, hacking

#830 Moved faq and provisioner to new reference section
  website/content/en/pre-docs/cloud-providers/AWS/aws-spec-fields.md
  website/content/en/pre-docs/reference/_index.md
  website/content/en/pre-docs/reference/faqs.md
  website/content/en/pre-docs/reference/provisioner-crd.md
Labels: documentation

#845 Add Running Pods task to docs
  website/content/en/pre-docs/tasks/_index.md
  website/content/en/pre-docs/tasks/running-pods.md
Labels: documentation

#844 update preview docs based on live docs
  website/content/en/pre-docs/_index.md
  website/content/en/pre-docs/concepts/_index.md
Labels: documentation

#868 delete Grafana docs
  website/content/en/pre-docs/getting-started/grafana-values.yaml
  website/content/en/pre-docs/getting-started/grafana.md
  website/content/en/pre-docs/getting-started/prometheus-values.yaml
Labels: documentation

#870 task: deprovision nodes
  website/content/en/pre-docs/tasks/deprov-nodes.md
Labels: documentation

#846 move and revise AWS constraints
  website/content/en/pre-docs/AWS/_index.md
  website/content/en/pre-docs/AWS/constraints.md
  website/content/en/pre-docs/AWS/launch-templates.md
  website/content/en/pre-docs/cloud-providers/AWS/aws-spec-fields.md
  website/content/en/pre-docs/cloud-providers/_index.md
  website/content/en/pre-docs/provisioner-crd.md
Labels: documentation
