Repository aws/karpenter-provider-aws, pull requests merged in 2021-12, with the labels that each got.

#879 patch broken urls
  website/content/en/docs/AWS/constraints.md
  website/content/en/docs/AWS/launch-templates.md
  website/content/en/docs/concepts/_index.md
  website/content/en/docs/provisioner-crd.md
  website/content/en/docs/tasks/deprov-nodes.md
  website/content/en/v0.4.3-docs/cloud-providers/AWS/launch-templates.md
  website/content/en/v0.4.3-docs/concepts/_index.md
Labels: documentation

#904 add robots.txt
  website/config.toml
  website/layouts/robots.txt
Labels: documentation

#906 feat: improve display of releases in navbar
  website/assets/scss/_variables_project.scss
  website/config.toml
  website/layouts/partials/navbar-version-selector.html
  website/layouts/partials/navbar.html
Labels: documentation, hacking

#873 fix yaml download cmds in grafana docs
  website/content/en/docs/getting-started/_index.md
  website/content/en/docs/getting-started/grafana-values.yaml
  website/content/en/docs/getting-started/prometheus-values.yaml
Labels: feature, observability
