Repository aws/karpenter-provider-aws, pull requests merged in 2021-08, with the labels that each got.

#592 add docs issue template
  .github/ISSUE_TEMPLATE/docs-request.md
Labels: Project Management

#618 Provisioner cluster endpoint validation
  go.sum
  pkg/apis/provisioning/v1alpha3/provisioner_validation.go
  pkg/apis/provisioning/v1alpha3/provisioner_validation_test.go
Labels: bug

#627 change guidance on installing go lang
  website/content/en/docs/development-guide.md
Labels: documentation

#623 fix link to subnet tagging in development guide
  website/content/en/docs/development-guide.md
Labels: documentation
